### PR TITLE
Pull request from gitman for issue number 135

### LINKED ISSUE #135: Issue with CSS
Need to change background from green to red.

### PR DESCRIPTION
**Pull request by troowala**
Pull request from gitman closes #135

### CODE REVIEW

**Comment by craigvl** [comment]
Hello, approving this pull request and you should then receive the reward into your wallet!

**Comment by craigvl** [comment]
@troowala can you confirm that you received your reward, thanks.

**Comment by troowala** [comment]
yes thanks ... seem to have recieved some as my balance increased but surprisingly doesnt show on rinkeby blockexplorer yet

https://rinkeby.etherscan.io/address/0x6641c30B8Ec57A6168707115b80B0af1a5cf160C

anyways all good , im sure it will catch up

great idea and excellent effort ! lookin forward to your mainnet launch , all the best

**Comment by craigvl** [comment]
@troowala thanks for trying it out! Yes etherscan is not always correct. We are working hard, creating an onboarding wizard, enabling private repos and general improvements. 

I will let you know when we have moved the app onto the mainnet.

Thanks again.

**Pull request merged**
